name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Deploy to EC2
      env:
        PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        HOST: 54.215.21.69
        USERNAME: ubuntu
      run: |
        eval $(ssh-agent -s)
        echo "$PRIVATE_KEY" | ssh-add -
        ssh -o StrictHostKeyChecking=no $USERNAME@$HOST "/home/ubuntu/.nvm/versions/node/v16.16.0/bin/npm install"
